### ISSUE TITLE
Normal logins and threebot logins can't have the same email

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/tf-peertube#2]
This is the default behaviour in peertube plugins. It doesn't allow mixing login flows. So once a user is registered using some method he can't use something else.

**Comment by weynandkuijpers** [comment]
Please u pdate and verify and close if done

**Comment by hossnys** [comment]
peertube chatflow is not asking for user mail now to avoid same email with multiple login flows issue and set default mail for admin

![Screenshot from 2021-03-21 19-21-20](https://user-images.githubusercontent.com/26298009/111914682-9deb8300-8a7b-11eb-88b5-d3fbea98b26f.png)

![Screenshot from 2021-03-21 19-20-21](https://user-images.githubusercontent.com/26298009/111914680-9cba5600-8a7b-11eb-864c-4d6d89bc3e03.png)
