### ISSUE TITLE
Add default admin mail and password in peertube chart 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/tf-peertube#5]
Add default admin mail and password so the user can change them later 
now we can safely login user threefold connect service

**Comment by RafyAmgadBenjamin** [comment]
### Fixed 
### Branch 
`peertube_fix`
### PR
https://github.com/threefoldtech/vdc-solutions-charts/pull/103

**Comment by hossnys** [comment]
verified 

![Screenshot from 2021-03-21 19-21-20](https://user-images.githubusercontent.com/26298009/111914765-13575380-8a7c-11eb-80fa-c6ab292b4df4.png)


![Screenshot from 2021-03-21 19-20-21](https://user-images.githubusercontent.com/26298009/111914764-12262680-8a7c-11eb-8bbd-8ea6f4d2eec9.png)
